#!/bin/bash

# Define the template file path
TEMPLATE_FILE="../src/Chapter02/ipynb_codes/0000_tmplate.ipynb"

echo "Starting to copy template files..."

mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0002_transpose_of_a_matrix.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0002_transpose_of_a_matrix.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0002_transpose_of_a_matrix.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0003_reshape_matrix.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0003_reshape_matrix.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0003_reshape_matrix.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0004_calculate_mean_by_row_or_column.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0004_calculate_mean_by_row_or_column.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0004_calculate_mean_by_row_or_column.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0005_scalar_multiplication_of_a_matrix.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0005_scalar_multiplication_of_a_matrix.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0005_scalar_multiplication_of_a_matrix.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0006_calculate_eigenvalues_of_a_matrix.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0006_calculate_eigenvalues_of_a_matrix.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0006_calculate_eigenvalues_of_a_matrix.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0007_matrix_transformation.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0007_matrix_transformation.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0007_matrix_transformation.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0008_calculate_2x2_matrix_inverse.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0008_calculate_2x2_matrix_inverse.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0008_calculate_2x2_matrix_inverse.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0009_matrix_times_matrix.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0009_matrix_times_matrix.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0009_matrix_times_matrix.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0010_calculate_covariance_matrix.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0010_calculate_covariance_matrix.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0010_calculate_covariance_matrix.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0011_solve_linear_equations_using_jacobi_method.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0011_solve_linear_equations_using_jacobi_method.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0011_solve_linear_equations_using_jacobi_method.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0012_singular_value_decomposition.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0012_singular_value_decomposition.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0012_singular_value_decomposition.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0013_determinant_of_a_4x4_matrix_using_laplace's_expansion.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0013_determinant_of_a_4x4_matrix_using_laplace's_expansion.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0013_determinant_of_a_4x4_matrix_using_laplace's_expansion.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0014_linear_regression_using_normal_equation.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0014_linear_regression_using_normal_equation.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0014_linear_regression_using_normal_equation.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0015_linear_regression_using_gradient_descent.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0015_linear_regression_using_gradient_descent.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0015_linear_regression_using_gradient_descent.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0016_feature_scaling_implementation.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0016_feature_scaling_implementation.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0016_feature_scaling_implementation.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0017_k-means_clustering.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0017_k-means_clustering.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0017_k-means_clustering.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0018_cross-validation_data_split_implementation.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0018_cross-validation_data_split_implementation.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0018_cross-validation_data_split_implementation.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0019_principal_component_analysis.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0019_principal_component_analysis.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0019_principal_component_analysis.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0020_decision_tree_learning.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0020_decision_tree_learning.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0020_decision_tree_learning.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0021_pegasos_kernel_svm_implementation.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0021_pegasos_kernel_svm_implementation.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0021_pegasos_kernel_svm_implementation.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0022_sigmoid_activation_function_understanding.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0022_sigmoid_activation_function_understanding.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0022_sigmoid_activation_function_understanding.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0023_softmax_activation_function_implementation.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0023_softmax_activation_function_implementation.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0023_softmax_activation_function_implementation.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0024_single_neuron.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0024_single_neuron.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0024_single_neuron.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0025_single_neuron_with_backpropagation.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0025_single_neuron_with_backpropagation.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0025_single_neuron_with_backpropagation.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0026_implementing_basic_autograd_operations.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0026_implementing_basic_autograd_operations.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0026_implementing_basic_autograd_operations.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0027_implementing_mlp_based_on_autograd_operations.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0027_implementing_mlp_based_on_autograd_operations.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0027_implementing_mlp_based_on_autograd_operations.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0028_transformation_matrix_from_basis_b_to_c.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0028_transformation_matrix_from_basis_b_to_c.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0028_transformation_matrix_from_basis_b_to_c.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0029_svd_of_a_2x2_matrix_using_eigen_values_&_vectors.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0029_svd_of_a_2x2_matrix_using_eigen_values_&_vectors.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0029_svd_of_a_2x2_matrix_using_eigen_values_&_vectors.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0030_random_shuffle_of_dataset.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0030_random_shuffle_of_dataset.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0030_random_shuffle_of_dataset.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0031_batch_iterator_for_dataset.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0031_batch_iterator_for_dataset.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0031_batch_iterator_for_dataset.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0032_divide_dataset_based_on_feature_threshold.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0032_divide_dataset_based_on_feature_threshold.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0032_divide_dataset_based_on_feature_threshold.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0033_generate_polynomial_features.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0033_generate_polynomial_features.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0033_generate_polynomial_features.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0034_generate_random_subsets_of_a_dataset.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0034_generate_random_subsets_of_a_dataset.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0034_generate_random_subsets_of_a_dataset.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0035_one-hot_encoding_of_nominal_values.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0035_one-hot_encoding_of_nominal_values.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0035_one-hot_encoding_of_nominal_values.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0036_convert_vector_to_diagonal_matrix.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0036_convert_vector_to_diagonal_matrix.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0036_convert_vector_to_diagonal_matrix.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0037_calculate_accuracy_score.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0037_calculate_accuracy_score.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0037_calculate_accuracy_score.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0038_calculate_correlation_matrix.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0038_calculate_correlation_matrix.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0038_calculate_correlation_matrix.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0039_implement_adaboost_fit_method.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0039_implement_adaboost_fit_method.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0039_implement_adaboost_fit_method.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0040_implementation_of_log_softmax_function.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0040_implementation_of_log_softmax_function.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0040_implementation_of_log_softmax_function.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0041_implementing_a_custom_dense_layer_in_python.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0041_implementing_a_custom_dense_layer_in_python.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0041_implementing_a_custom_dense_layer_in_python.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0042_simple_convolutional_2d_layer.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0042_simple_convolutional_2d_layer.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0042_simple_convolutional_2d_layer.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0043_implement_relu_activation_function.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0043_implement_relu_activation_function.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0043_implement_relu_activation_function.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0044_implement_ridge_regression_loss_function.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0044_implement_ridge_regression_loss_function.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0044_implement_ridge_regression_loss_function.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0045_leaky_relu_activation_function.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0045_leaky_relu_activation_function.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0045_leaky_relu_activation_function.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0046_linear_kernel_function.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0046_linear_kernel_function.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0046_linear_kernel_function.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0047_implement_precision_metric.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0047_implement_precision_metric.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0047_implement_precision_metric.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0048_implement_gradient_descent_variants_with_mse_loss.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0048_implement_gradient_descent_variants_with_mse_loss.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0048_implement_gradient_descent_variants_with_mse_loss.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0049_implement_reduced_row_echelon_form_(rref)_function.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0049_implement_reduced_row_echelon_form_(rref)_function.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0049_implement_reduced_row_echelon_form_(rref)_function.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0050_implement_adam_optimization_algorithm.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0050_implement_adam_optimization_algorithm.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0050_implement_adam_optimization_algorithm.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0051_implement_lasso_regression_using_gradient_descent.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0051_implement_lasso_regression_using_gradient_descent.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0051_implement_lasso_regression_using_gradient_descent.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0052_optimal_string_alignment_distance.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0052_optimal_string_alignment_distance.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0052_optimal_string_alignment_distance.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0053_implement_recall_metric_in_binary_classification.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0053_implement_recall_metric_in_binary_classification.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0053_implement_recall_metric_in_binary_classification.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0054_implement_self-attention_mechanism.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0054_implement_self-attention_mechanism.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0054_implement_self-attention_mechanism.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0055_implementing_a_simple_rnn.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0055_implementing_a_simple_rnn.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0055_implementing_a_simple_rnn.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0056_2d_translation_matrix_implementation.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0056_2d_translation_matrix_implementation.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0056_2d_translation_matrix_implementation.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0057_kl_divergence_between_two_normal_distributions.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0057_kl_divergence_between_two_normal_distributions.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0057_kl_divergence_between_two_normal_distributions.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0058_gauss-seidel_method_for_solving_linear_systems.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0058_gauss-seidel_method_for_solving_linear_systems.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0058_gauss-seidel_method_for_solving_linear_systems.ipynb"
mkdir -p "$(dirname "../src/Chapter02/ipynb_codes/0059_gaussian_elimination_for_solving_linear_systems.ipynb")"
cp "$TEMPLATE_FILE" "../src/Chapter02/ipynb_codes/0059_gaussian_elimination_for_solving_linear_systems.ipynb"
echo "Copied to ../src/Chapter02/ipynb_codes/0059_gaussian_elimination_for_solving_linear_systems.ipynb"

echo "All files have been copied."
